services:
  app:
    image: betatester-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command:
      - python
      - -m
      - uvicorn
      - betatester.server:app
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
      - --reload
    environment:
      ENVIRONMENT: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./app-data:/app-data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always