services:
  app:
    image: betatester-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    command:
      - python
      - -m
      - uvicorn
      - betatester_web_service.server:app
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
      - --reload
      - --reload-include
      - "../python_package/*"
    environment:
      ENVIRONMENT: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./app-data:/app-data
      - ./python_package:/python_package
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always